import { Exercise } from '../types';

export const defaultExercises: Exercise[] = [
  // Chest - Double progression (barbell/dumbbell exercises)
  {
    id: 'bench-press',
    name: 'Bench Press',
    category: 'chest',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    progressionType: 'double',
    weightIncrement: 5,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 3,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'incline-bench-press',
    name: 'Incline Bench Press',
    category: 'chest',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    progressionType: 'double',
    weightIncrement: 5,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 3,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    category: 'chest',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    progressionType: 'double',
    weightIncrement: 5,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 3,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    category: 'chest',
    muscleGroups: ['chest'],
    progressionType: 'triple',
    weightIncrement: 10,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },

  // Back
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    category: 'back',
    muscleGroups: ['back', 'biceps'],
    progressionType: 'double',
    weightIncrement: 5,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 3,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'back',
    muscleGroups: ['back', 'biceps'],
    progressionType: 'triple',
    weightIncrement: 10,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cable-row',
    name: 'Seated Cable Row',
    category: 'back',
    muscleGroups: ['back', 'biceps'],
    progressionType: 'triple',
    weightIncrement: 10,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pull-ups',
    name: 'Pull-ups',
    category: 'back',
    muscleGroups: ['back', 'biceps'],
    progressionType: 'triple',
    weightIncrement: 5,
    targetRepMin: 6,
    targetRepMax: 12,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    category: 'back',
    muscleGroups: ['back', 'legs', 'core'],
    progressionType: 'double',
    weightIncrement: 10,
    targetRepMin: 5,
    targetRepMax: 8,
    targetSetsMin: 3,
    targetSetsMax: 5,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },

  // Shoulders
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    category: 'shoulders',
    muscleGroups: ['shoulders', 'triceps'],
    progressionType: 'double',
    weightIncrement: 5,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 3,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    category: 'shoulders',
    muscleGroups: ['shoulders'],
    progressionType: 'triple',
    weightIncrement: 5,
    targetRepMin: 10,
    targetRepMax: 15,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    category: 'shoulders',
    muscleGroups: ['shoulders', 'back'],
    progressionType: 'triple',
    weightIncrement: 10,
    targetRepMin: 12,
    targetRepMax: 20,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },

  // Biceps
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    category: 'biceps',
    muscleGroups: ['biceps'],
    progressionType: 'double',
    weightIncrement: 5,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 3,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    category: 'biceps',
    muscleGroups: ['biceps'],
    progressionType: 'triple',
    weightIncrement: 5,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cable-curl',
    name: 'Cable Curl',
    category: 'biceps',
    muscleGroups: ['biceps'],
    progressionType: 'triple',
    weightIncrement: 10,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },

  // Triceps
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    category: 'triceps',
    muscleGroups: ['triceps'],
    progressionType: 'triple',
    weightIncrement: 10,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    category: 'triceps',
    muscleGroups: ['triceps'],
    progressionType: 'triple',
    weightIncrement: 10,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'skull-crushers',
    name: 'Skull Crushers',
    category: 'triceps',
    muscleGroups: ['triceps'],
    progressionType: 'double',
    weightIncrement: 5,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 3,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },

  // Legs
  {
    id: 'squat',
    name: 'Squat',
    category: 'legs',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    progressionType: 'double',
    weightIncrement: 10,
    targetRepMin: 6,
    targetRepMax: 10,
    targetSetsMin: 3,
    targetSetsMax: 5,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'legs',
    muscleGroups: ['quadriceps', 'glutes'],
    progressionType: 'double',
    weightIncrement: 10,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 3,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'legs',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    progressionType: 'double',
    weightIncrement: 10,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 3,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    category: 'legs',
    muscleGroups: ['hamstrings'],
    progressionType: 'triple',
    weightIncrement: 10,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    category: 'legs',
    muscleGroups: ['quadriceps'],
    progressionType: 'triple',
    weightIncrement: 10,
    targetRepMin: 8,
    targetRepMax: 12,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'calf-raise',
    name: 'Calf Raise',
    category: 'legs',
    muscleGroups: ['calves'],
    progressionType: 'triple',
    weightIncrement: 10,
    targetRepMin: 12,
    targetRepMax: 20,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },

  // Core
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    category: 'core',
    muscleGroups: ['abs'],
    progressionType: 'triple',
    weightIncrement: 10,
    targetRepMin: 10,
    targetRepMax: 15,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    muscleGroups: ['abs', 'core'],
    progressionType: 'triple',
    weightIncrement: 0,
    targetRepMin: 30,
    targetRepMax: 60,
    targetSetsMin: 2,
    targetSetsMax: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
];

export const categoryLabels: Record<string, string> = {
  chest: 'Chest',
  back: 'Back',
  shoulders: 'Shoulders',
  biceps: 'Biceps',
  triceps: 'Triceps',
  legs: 'Legs',
  core: 'Core',
  cardio: 'Cardio',
  compound: 'Compound',
};
